name: Generate Listing Pages

on:
  push:
    paths:
      - 'data/config.json'
  workflow_dispatch: # Manual trigger

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      
      - name: Generate pages
        run: |
          node scripts/generate-pages.js
      
      - name: Commit and push generated pages
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add listings/*.html
          git diff --staged --quiet || git commit -m "Auto-generate listing pages"
          git push

